NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 20
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 0
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = 0
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0

NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 100
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 6
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 100
NDefines.NDiplomacy.TRIBUTE_BASE_CASH = 0.05
NDefines.NDiplomacy.TRIBUTE_BASE_ADM = 0.01
NDefines.NDiplomacy.TRIBUTE_BASE_DIP = 0.01
NDefines.NDiplomacy.TRIBUTE_BASE_MIL = 0.01
NDefines.NDiplomacy.TRIBUTE_REFUSED_TRUST = -1
NDefines.NDiplomacy.TRIBUTE_MAX_MONARCH_POWER = 3.0
NDefines.NDiplomacy.TRIBUTE_BASE_MANPOWER = 0.1
NDefines.NCountry.BREAK_TRIBUTARY_STABILITY_PENALTY = 0

NDefines.NMilitary.BANNER_MANPOWER_USAGE = 1
NDefines.NMilitary.BANNER_MAINTENANCE_COST = 1
NDefines.NMilitary.BANNER_AGE_MULTIPLIER = 0

NDefines.NAI.PEACE_MANDATE_THREAT_FACTOR = 0